site_name: Smart People Automate
site_author: Oliver Jakoubek
site_url: https://www.smartpeopleautomate.de/

nav:
  - Start:
    - 'index.md'
    - Tags: tags.md
  - Tools:
    - 'tools/index.md'

theme:
  name: material
  language: de
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
  highlightjs: true

copyright: Copyright &copy; 2022 <a href="https://www.smartpeopleautomate.de/">Smart People Automate</a>

plugins:
  - tags:
      tags_file: tags.md
  - search:
      lang:
        - de
        - en
  - macros

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - meta
